### ISSUE TITLE
isLong in sexp causes index out of range error

### ISSUE THREAD

**Issue by vamitrou** [senseyeio/roger#22]
This line throws an error in case of big outputs:

https://github.com/senseyeio/roger/blob/master/sexp/factory.go#L19

I am trying to export ~30 Mbytes JSON output from R.

Commenting this block out solves the issue.

Could you spare some info?

**Comment by dareid** [comment]
Hopefully this issue has been fixed. If you could let me know if it hasn't and I can have another look.
Thanks for raising the issue!
