### ISSUE TITLE
Unsupported expression type: 23 (XT_LANG_TAG)

### ISSUE THREAD

**Issue by bfallik** [senseyeio/roger#30]
roger seems unable to handle this type. If I try:
```
  rClient.EvaluateSync("try(source('does not exist'))")
```

Based on this [header](https://github.com/s-u/Rserve/blob/5a7cb7bfd7ea6df17dc239357473c2d867fc5271/src/Rsrv.h#L307) it seems like the missing sexp type is XT_LANG_TAG.

**Comment by bfallik** [comment]
Wow, fortunately timing - it looks like this might be addressed in https://github.com/senseyeio/roger/pull/27.

**Comment by dareid** [comment]
#27 has now been merged. Hopefully this closes this issue. Feel free to reopen if you have issues still.
