### ISSUE TITLE
Error on common.go

### ISSUE THREAD

**Issue by predixdeveloperACN** [senseyeio/roger#34]
I'm having this issue:

$ go build
# github.com/senseyeio/roger/assign

......\github.com\senseyeio\roger\assign\common.go:27: constant 4278190080 overflows int
......\github.com\senseyeio\roger\assign\common.go:45: constant 4278190080 overflows int

I believe this is because of data type int which can't handle the shift >> 24.

**Comment by TheCodeBuccaneer** [comment]
Facing the same issue here/
